// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:courier/core/storage/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AuthHiveModelAdapter());
    registerAdapter(EnvironmentHiveModelAdapter());
    registerAdapter(HistoryEntryHiveModelAdapter());
    registerAdapter(KeyValueHiveModelAdapter());
    registerAdapter(RequestHiveModelAdapter());
    registerAdapter(ResponseHiveModelAdapter());
    registerAdapter(SavedRequestHiveModelAdapter());
    registerAdapter(SettingsHiveModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AuthHiveModelAdapter());
    registerAdapter(EnvironmentHiveModelAdapter());
    registerAdapter(HistoryEntryHiveModelAdapter());
    registerAdapter(KeyValueHiveModelAdapter());
    registerAdapter(RequestHiveModelAdapter());
    registerAdapter(ResponseHiveModelAdapter());
    registerAdapter(SavedRequestHiveModelAdapter());
    registerAdapter(SettingsHiveModelAdapter());
  }
}
